// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// tl_1to2 package generated by `tlgen.py` tool

package tl_1to2_pkg;

  localparam logic [31:0] ADDR_SPACE_SRAM = 32'h 20000000;
  localparam logic [31:0] ADDR_SPACE_MAIN = 32'h 30000000;

  localparam logic [31:0] ADDR_MASK_SRAM = 32'h 0fffffff;
  localparam logic [31:0] ADDR_MASK_MAIN = 32'h 0fffffff;

  localparam int N_HOST   = 1;
  localparam int N_DEVICE = 2;

  typedef enum int {
    TlSram = 0,
    TlMain = 1
  } tl_device_e;

  typedef enum int {
    TlCore = 0
  } tl_host_e;

endpackage
