// Copyright lowRISC contributors.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_2to1 module generated by `tlgen.py` tool
// all reset signals should be generated from one reset signal to not make any deadlock
//
// Interconnect
// core
//   -> sm1_3
//     -> sram
// main
//   -> sm1_3
//     -> sram

module xbar_2to1 (
  input clk_i,
  input rst_ni,

  // Host interfaces
  input  tlul_pkg::tl_h2d_t tl_core_i,
  output tlul_pkg::tl_d2h_t tl_core_o,
  input  tlul_pkg::tl_h2d_t tl_main_i,
  output tlul_pkg::tl_d2h_t tl_main_o,

  // Device interfaces
  output tlul_pkg::tl_h2d_t tl_sram_o,
  input  tlul_pkg::tl_d2h_t tl_sram_i,

  input prim_mubi_pkg::mubi4_t scanmode_i
);

  import tlul_pkg::*;

  // scanmode_i is currently not used, but provisioned for future use
  // this assignment prevents lint warnings
  logic unused_scanmode;
  assign unused_scanmode = ^scanmode_i;

  tl_h2d_t tl_sm1_3_us_h2d [2];
  tl_d2h_t tl_sm1_3_us_d2h [2];

  tl_h2d_t tl_sm1_3_ds_h2d ;
  tl_d2h_t tl_sm1_3_ds_d2h ;

  assign tl_sram_o = tl_sm1_3_ds_h2d;
  assign tl_sm1_3_ds_d2h = tl_sram_i;

  assign tl_sm1_3_us_h2d[0] = tl_core_i;
  assign tl_core_o = tl_sm1_3_us_d2h[0];

  assign tl_sm1_3_us_h2d[1] = tl_main_i;
  assign tl_main_o = tl_sm1_3_us_d2h[1];

  // Instantiation phase
  tlul_socket_m1 #(
    .HReqDepth (8'h0),
    .HRspDepth (8'h0),
    .DReqDepth (4'h0),
    .DRspDepth (4'h0),
    .M         (2)
  ) u_sm1_3 (
    .clk_i        (clk_i),
    .rst_ni       (rst_ni),
    .tl_h_i       (tl_sm1_3_us_h2d),
    .tl_h_o       (tl_sm1_3_us_d2h),
    .tl_d_o       (tl_sm1_3_ds_h2d),
    .tl_d_i       (tl_sm1_3_ds_d2h)
  );

endmodule
